Dataset options

1.job_dataset has 1,068 rows,218 uniques job titles.
The output varaible expected are job titles .By having the skills and experiencelevel the model predicts the most suitable job title the student can be qualify for .

2.Tech_data_cleaned.csv has 1161 rows of 1147 unique job roles acrross 28 field and the expected output variable is to give job roles (field) ,by given the student known programming lanaguages or skills it predicts the matching roles the student can fit in .

3.Top_207_IT_Job_roles:was the smallest dataset with 207 rows and 200 uniques job titles .The output variable is to generate job titles and certification needed based on the skills and certifications a student has .

4.Roadmap.sh_dataset:was the largest dataset over 10634 rows and the output variable is to give career path over the 93 tech career paths which fit best to the student interested path and then surfaces the associated topics nodes they have to learn to reach their intended career.

The choice of the dataset

The choice of the Dataset was support by the main goal of the ML Model we want to implement for our project in brief

" TechPath seeks to bridge the gap between university education and technology career readiness. Many students know they want to enter the technology industry but do not necessarily know what career path to follow, what skills they need, what projects or experience they should gain, or where to find relevant opportunities.
" .

Why this dataset ?reason being the output variable is to give a career_path so it containt detailed and well structure informations to assist in the training process of the model.

The model will take student input (skills,path of interest) and predict the most relevant tech career path to follow from the available dataset ,which then determines which roadmap topics to give to the student .

The set up

In [5]:
from google.colab import drive
drive.mount('/content/drive')
#let import the dataset we are using for our project and read its content
import pandas as pd
dataset = pd.read_csv('/content/drive/MyDrive/Data/Dataset.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
#for testing
dataset.head()

,career_path,topic_slug,node_id,title,description,courses,articles,official_docs,videos,opensource
0,ai-agents,acting--tool-invocation,sHYd4KsKlmw5Im3nQ19W8,Acting / Tool Invocation,"Acting, also called tool invocation, is the st...",NaN,What are Tools in AI Agents? (https://huggingf...,NaN,NaN,NaN
1,ai-agents,agent-loop,Eih4eybuYB3C2So8K0AT3,Agent Loop,An agent loop is the cycle that lets an AI age...,NaN,What is an Agent Loop? (https://huggingface.co...,NaN,NaN,NaN
2,ai-agents,agno,PY5WTJgRnXiYeOM6BBUvn,Agno,Agno is a Python framework designed to streaml...,NaN,NaN,Agno Docs (https://docs.agno.com/),Building Your First Agent With AGNO AGI ( Prev...,agno (https://github.com/agno-agi/agno)
3,ai-agents,anthropic-tool-use,1EZFbDHA5J5_5BPMLMxXb,Anthropic Tool Use,Anthropic Tool Use lets you connect a Claude m...,NaN,NaN,Anthropic Tool Use (https://docs.anthropic.com...,NaN,NaN
4,ai-agents,api-requests,52qxjZILV-X1isup6dazC,API Requests,API requests let an AI agent ask another servi...,NaN,Introduction to APIs - MDN Web Docs (https://d...,NaN,NaN,NaN

Question 1

In [9]:
#Using the shape property which return a result like this [row,colums ] number
row,column =dataset.shape
print(F"Our dataset has {row} rows and {column} columns")

Our dataset has 10634 rows and 10 columns

Question 2

In [10]:
# to have the datatype of the content we used dtypes property
dataset.dtypes

career_path      object
topic_slug       object
node_id          object
title            object
description      object
courses          object
articles         object
official_docs    object
videos           object
opensource       object
dtype: object

Question 3

In [13]:
#To detect and sum up missing values
missing_object=dataset.isnull().sum()
if missing_object.sum()==0 :
  print("The dataset is complete")
else:
  print(f"The dataset has {missing_object.sum()} missing values")

print(missing_object)

The dataset has 36539 missing values
career_path          0
topic_slug          19
node_id              9
title                2
description         29
courses          10335
articles          3634
official_docs     5987
videos            6337
opensource       10187
dtype: int64

Question 4

In [14]:
#Now we are going to create an sample of the dataset by taking the fisr 15 and last 20 rows
first_15 =dataset.head(15)
last_20=dataset.tail(20)

#we put then them in a new dataframe called df_sample
df_sample=pd.concat([first_15,last_20])

#Here is the Sample data
df_sample

,career_path,topic_slug,node_id,title,description,courses,articles,official_docs,videos,opensource
0,ai-agents,acting--tool-invocation,sHYd4KsKlmw5Im3nQ19W8,Acting / Tool Invocation,"Acting, also called tool invocation, is the st...",NaN,What are Tools in AI Agents? (https://huggingf...,NaN,NaN,NaN
1,ai-agents,agent-loop,Eih4eybuYB3C2So8K0AT3,Agent Loop,An agent loop is the cycle that lets an AI age...,NaN,What is an Agent Loop? (https://huggingface.co...,NaN,NaN,NaN
2,ai-agents,agno,PY5WTJgRnXiYeOM6BBUvn,Agno,Agno is a Python framework designed to streaml...,NaN,NaN,Agno Docs (https://docs.agno.com/),Building Your First Agent With AGNO AGI ( Prev...,agno (https://github.com/agno-agi/agno)
3,ai-agents,anthropic-tool-use,1EZFbDHA5J5_5BPMLMxXb,Anthropic Tool Use,Anthropic Tool Use lets you connect a Claude m...,NaN,NaN,Anthropic Tool Use (https://docs.anthropic.com...,NaN,NaN
4,ai-agents,api-requests,52qxjZILV-X1isup6dazC,API Requests,API requests let an AI agent ask another servi...,NaN,Introduction to APIs - MDN Web Docs (https://d...,NaN,NaN,NaN
5,ai-agents,autogen,7YtnQ9-KIvGPSpDzEDexl,AutoGen,AutoGen is an open-source Python framework tha...,NaN,NaN,AutoGen - Microsoft Research (https://www.micr...,NaN,GitHub - microsoft/autogen (https://github.com...
6,ai-agents,basic-backend-development,VPI89s-m885r2YrXjYxdd,Basic Backend Development,Before you start learning how to build AI agen...,NaN,Introduction to the server-side (https://devel...,NaN,NaN,NaN
7,ai-agents,be-specific-in-what-you-want,qFKFM2qNPEN7EoD0V-1SM,Be specific in what you want,"When you ask an AI to do something, clear and ...",NaN,Prompt Engineering Guide (https://www.promptin...,NaN,NaN,NaN
8,ai-agents,bias--toxicity-guardrails,EyLo2j8IQsIK91SKaXkmK,Bias & Toxicity Guardrails,Bias and toxicity guardrails keep an AI agent ...,NaN,Define the Agent Guardrails (https://trailhead...,NaN,NaN,NaN
9,ai-agents,chain-of-thought-cot,qwdh5pkBbrF8LKPxbZp4F,Chain of Thought (CoT),Chain of Thought (CoT) is a way for an AI agen...,NaN,Chain-of-Thought Prompting Elicits Reasoning i...,NaN,NaN,NaN
10,ai-agents,closed-weight-models,tJYmEDDwK0LtEux-kwp9B,Closed Weight Models,Closed-weight models are AI systems whose trai...,NaN,Open-Source LLMs vs Closed LLMs (https://hatch...,Open AI's GPT-4 (https://openai.com/gpt-4) | C...,NaN,NaN
11,ai-agents,code-execution--repl,mS0EVCkWuPN_GkVPng4A2,Code Execution / REPL,Code Execution or REPL (Read-Eval-Print Loop) ...,NaN,What is a REPL? (https://docs.replit.com/getti...,NaN,NaN,NaN
12,ai-agents,code-generation,PK8w31GlvtmAuU92sHaqr,Code generation,Code-generation agents take a plain language r...,NaN,Multi-Agent-based Code Generation (https://arx...,GitHub Copilot (https://github.com/features/co...,NaN,NaN
13,ai-agents,context-windows,dyn1LSioema-Bf9lLTgUZ,Context Windows,A context window is the chunk of text a large ...,NaN,What is a Context Window in AI? (https://www.i...,NaN,NaN,NaN
14,ai-agents,creating-mcp-servers,1NXIN-Hbjl5rPy_mqxQYW,Creating MCP Servers,An MCP server stores and shares conversation d...,NaN,How to Build and Host Your Own MCP Servers in ...,Model Context Protocol (MCP) Specification (ht...,NaN,NaN
10614,wordpress,transients-api,WXTnOWylTg4aLn8r1mdwS,Transients API,The Transients API in WordPress provides a sim...,NaN,A Guide to Transients in WordPress (https://wp...,An introduction to the Transients API (https:/...,NaN,NaN
10615,wordpress,universal,wlFxhJTD3VZBhRTWKHaT6,Universal Themes,Universal themes were the initial iteration of...,NaN,Choosing and installing a theme (https://learn...,Different types of themes (https://wordpress.c...,Choosing and installing a theme (https://www.y...,NaN
10616,wordpress,update-strategies,AGQ9uXMYuYQ5d6w56gJBP,Update Strategies,Updating WordPress involves keeping your core ...,NaN,How To Update WordPress Without Breaking Your ...,NaN,WordPress Updates 101 (and Beyond) (https://ww...,NaN
10617,wordpress,user--login-security,1737UjumNSgI4woESMn49,User & Login Security,User and login security focus on protecting us...,NaN,What is 2FA? A beginner’s guide (https://melap...,NaN,Simple WordPress Security Wins - How to Protec...,NaN
10618,wordpress,user-roles,KR9cp-nDEGTab4vmz0XBZ,User Roles,User roles define the capabilities and permiss...,NaN,How to use WordPress user roles for improved W...,Roles and Capabilities (https://wordpress.org/...,Adding custom user roles using a WordPress plu...,NaN
10619,wordpress,virtual-patching,GkaZLnXVhHqn2sQfChor7,Virtual Patching,Virtual patching is a security policy enforcem...,NaN,"Virtual Patching, Your WordPress Website’s Fir...",NaN,What is Virtual Patching & How Does It Work? (...,NaN
10620,wordpress,vps,7p44mAXvgrxoeJU1h0sP1,VPS Hosting for WordPress,A Virtual Private Server (VPS) provides a virt...,NaN,What is a VPS (Virtual Private Server)? (https...,NaN,How to Install WordPress on a VPS | QUICK & EA...,NaN
10621,wordpress,vulnerability-monitoring,pdoRrBaVwVTGCaJH4kY60,Vulnerability Monitoring,Vulnerability monitoring is the process of con...,NaN,What is vulnerability monitoring in WordPress?...,NaN,How Hackers Find Vulnerabilities in WordPress ...,NaN
10622,wordpress,vvv,4z0UM3vkE2m01G5vfH2rv,VVV,VVV (Varying Vagrant Vagrants) is an open-sour...,NaN,How to Use Varying Vagrant Vagrants (VVV) for ...,VVV (https://varyingvagrantvagrants.org/) | In...,NaN,varying-vagrant-vagrants (https://github.com/V...
10623,wordpress,what-is-a-cms,zc99eitvwwv7EmMRjhOSE,What is a CMS?,"A Content Management System (CMS), such as Wor...",NaN,Content management system (https://en.wikipedi...,NaN,What Is A CMS? - What Is Web Development (http...,NaN
10624,wordpress,what-is-http,LmEWD_XxAfoGvFqvmcT7Q,HTTP Explained,"HTTP, or Hypertext Transfer Protocol, is the f...",NaN,Everything you need to know about HTTP (https:...,NaN,NaN,NaN
10625,wordpress,widgets,DzXBl8O1uwq_DgyD88qRq,Widgets,Widgets are small blocks of content that you c...,NaN,The Complete Guide to WordPress Widgets: How t...,Widgets (https://wordpress.com/support/widgets...,WordPress Widgets: The Complete Guide (https:/...,NaN
10626,wordpress,wordpress-credit-program,0FtAQxN7lVZcTOVjbffvW,WordPress Credit Program,The WordPress Credit Program recognizes and re...,NaN,NaN,WordPress Credits (https://learn.wordpress.org...,NaN,NaN
10627,wordpress,wordpress-rest-api,gpO6iYnsepFTjbYzUEET0,WordPress REST API,The WordPress REST API is an interface that al...,NaN,The Complete Guide to WordPress REST API Basic...,REST API Handbook (https://developer.wordpress...,The WordPress REST API (https://www.youtube.co...,NaN
10628,wordpress,wordpresscom--wordpressorg,k9-YjpBsN8ID0haGR6ucq,WordPress.com vs. WordPress.org,WordPress offers two distinct platforms: [Word...,NaN,NaN,WordPress.com vs. WordPress.org (https://wordp...,WordPress.org VS WordPress.com: The Confusing ...,NaN
10629,wordpress,workflows--automation,5IJERQdGXAGLi7GDDBBUP,Workflows & Automation,Workflows and automation involve streamlining ...,NaN,Advanced WordPress automation workflows for ag...,NaN,NaN,NaN
10630,wordpress,working-with-databases,GzR7xWWm3m1laoQrQmbDZ,Working with Databases in Advanced Plugins,You can enhance the functionalities of plugins...,NaN,NaN,NaN,NaN,NaN
10631,wordpress,wp-cli,CNWRqhsaWK6xrIDvN564O,WP-CLI,WP-CLI is a command-line interface for WordPre...,NaN,How to Use the WordPress Command Line Interfac...,WP-CLI (https://wp-cli.org/) | WP-CLI Commands...,The Only WP CLI Tutorial You’ll Ever Need (htt...,NaN
10632,wordpress,wp_debug,InInDsldD3V7MHYCV7c89,WP_DEBUG,`WP_DEBUG` is a PHP constant in WordPress that...,NaN,A Complete Guide to WordPress Debugging (Enabl...,Debugging in WordPress (https://developer.word...,Debugging in WordPress (https://www.youtube.co...,NaN
10633,wordpress,xampp,Giqhdf6bmqsgEkCZ-aa65,XAMPP,XAMPP is a free and open-source cross-platform...,NaN,How to Use XAMPP: A 3-Step Guide to Setting Up...,XAMPP (https://www.apachefriends.org/) | Insta...,How to Install WordPress locally in Xampp Loca...,NaN